//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoORM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCOS
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> FechaLanzamiento { get; set; }
        public Nullable<int> CantidadCanciones { get; set; }
        public string UrlImagenTapa { get; set; }
        public Nullable<int> IdEstilo { get; set; }
        public Nullable<int> IdTipoEdicion { get; set; }
    }
}
