//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoORM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DISCOS_DBEntities : DbContext
    {
        public DISCOS_DBEntities()
            : base("name=DISCOS_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DISCOS> DISCOS { get; set; }
        public virtual DbSet<ESTILOS> ESTILOS { get; set; }
        public virtual DbSet<TIPOSEDICION> TIPOSEDICION { get; set; }
    }
}
